# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: future.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='future.proto',
  package='future',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x66uture.proto\x12\x06\x66uture\"\x98\x01\n\nfuture_min\x12\x0c\n\x04high\x18\x01 \x02(\x02\x12\x0b\n\x03low\x18\x02 \x02(\x02\x12\x0c\n\x04open\x18\x03 \x02(\x02\x12\r\n\x05\x63lose\x18\x04 \x02(\x02\x12\x0e\n\x06volume\x18\x05 \x02(\x02\x12\x0f\n\x07\x62\x61rtime\x18\x06 \x02(\t\x12\x12\n\nbarendtime\x18\x07 \x02(\t\x12\x10\n\x08turnover\x18\x08 \x02(\x02\x12\x0b\n\x03\x64\x61y\x18\t \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FUTURE_MIN = _descriptor.Descriptor(
  name='future_min',
  full_name='future.future_min',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='high', full_name='future.future_min.high', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='low', full_name='future.future_min.low', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='open', full_name='future.future_min.open', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='close', full_name='future.future_min.close', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volume', full_name='future.future_min.volume', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bartime', full_name='future.future_min.bartime', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='barendtime', full_name='future.future_min.barendtime', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='turnover', full_name='future.future_min.turnover', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='day', full_name='future.future_min.day', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=177,
)

DESCRIPTOR.message_types_by_name['future_min'] = _FUTURE_MIN

future_min = _reflection.GeneratedProtocolMessageType('future_min', (_message.Message,), dict(
  DESCRIPTOR = _FUTURE_MIN,
  __module__ = 'future_pb2'
  # @@protoc_insertion_point(class_scope:future.future_min)
  ))
_sym_db.RegisterMessage(future_min)


# @@protoc_insertion_point(module_scope)
