// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: future_min.proto

public final class FutureMin {
  private FutureMin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface future_minOrBuilder extends
      // @@protoc_insertion_point(interface_extends:future_min)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float high = 1;</code>
     */
    boolean hasHigh();
    /**
     * <code>required float high = 1;</code>
     */
    float getHigh();

    /**
     * <code>required float low = 2;</code>
     */
    boolean hasLow();
    /**
     * <code>required float low = 2;</code>
     */
    float getLow();

    /**
     * <code>required float open = 3;</code>
     */
    boolean hasOpen();
    /**
     * <code>required float open = 3;</code>
     */
    float getOpen();

    /**
     * <code>required float close = 4;</code>
     */
    boolean hasClose();
    /**
     * <code>required float close = 4;</code>
     */
    float getClose();

    /**
     * <code>required float volume = 5;</code>
     */
    boolean hasVolume();
    /**
     * <code>required float volume = 5;</code>
     */
    float getVolume();

    /**
     * <code>required string bartime = 6;</code>
     */
    boolean hasBartime();
    /**
     * <code>required string bartime = 6;</code>
     */
    java.lang.String getBartime();
    /**
     * <code>required string bartime = 6;</code>
     */
    com.google.protobuf.ByteString
        getBartimeBytes();

    /**
     * <code>required string barendtime = 7;</code>
     */
    boolean hasBarendtime();
    /**
     * <code>required string barendtime = 7;</code>
     */
    java.lang.String getBarendtime();
    /**
     * <code>required string barendtime = 7;</code>
     */
    com.google.protobuf.ByteString
        getBarendtimeBytes();

    /**
     * <code>required float turnover = 8;</code>
     */
    boolean hasTurnover();
    /**
     * <code>required float turnover = 8;</code>
     */
    float getTurnover();

    /**
     * <code>required string day = 9;</code>
     */
    boolean hasDay();
    /**
     * <code>required string day = 9;</code>
     */
    java.lang.String getDay();
    /**
     * <code>required string day = 9;</code>
     */
    com.google.protobuf.ByteString
        getDayBytes();
  }
  /**
   * Protobuf type {@code future_min}
   */
  public static final class future_min extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:future_min)
      future_minOrBuilder {
    // Use future_min.newBuilder() to construct.
    private future_min(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private future_min(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final future_min defaultInstance;
    public static future_min getDefaultInstance() {
      return defaultInstance;
    }

    public future_min getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private future_min(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              high_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              low_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              open_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              close_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              volume_ = input.readFloat();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              bartime_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              barendtime_ = bs;
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              turnover_ = input.readFloat();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              day_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FutureMin.internal_static_future_min_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FutureMin.internal_static_future_min_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FutureMin.future_min.class, FutureMin.future_min.Builder.class);
    }

    public static com.google.protobuf.Parser<future_min> PARSER =
        new com.google.protobuf.AbstractParser<future_min>() {
      public future_min parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new future_min(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<future_min> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HIGH_FIELD_NUMBER = 1;
    private float high_;
    /**
     * <code>required float high = 1;</code>
     */
    public boolean hasHigh() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float high = 1;</code>
     */
    public float getHigh() {
      return high_;
    }

    public static final int LOW_FIELD_NUMBER = 2;
    private float low_;
    /**
     * <code>required float low = 2;</code>
     */
    public boolean hasLow() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float low = 2;</code>
     */
    public float getLow() {
      return low_;
    }

    public static final int OPEN_FIELD_NUMBER = 3;
    private float open_;
    /**
     * <code>required float open = 3;</code>
     */
    public boolean hasOpen() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float open = 3;</code>
     */
    public float getOpen() {
      return open_;
    }

    public static final int CLOSE_FIELD_NUMBER = 4;
    private float close_;
    /**
     * <code>required float close = 4;</code>
     */
    public boolean hasClose() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float close = 4;</code>
     */
    public float getClose() {
      return close_;
    }

    public static final int VOLUME_FIELD_NUMBER = 5;
    private float volume_;
    /**
     * <code>required float volume = 5;</code>
     */
    public boolean hasVolume() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required float volume = 5;</code>
     */
    public float getVolume() {
      return volume_;
    }

    public static final int BARTIME_FIELD_NUMBER = 6;
    private java.lang.Object bartime_;
    /**
     * <code>required string bartime = 6;</code>
     */
    public boolean hasBartime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string bartime = 6;</code>
     */
    public java.lang.String getBartime() {
      java.lang.Object ref = bartime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bartime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string bartime = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBartimeBytes() {
      java.lang.Object ref = bartime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bartime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BARENDTIME_FIELD_NUMBER = 7;
    private java.lang.Object barendtime_;
    /**
     * <code>required string barendtime = 7;</code>
     */
    public boolean hasBarendtime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string barendtime = 7;</code>
     */
    public java.lang.String getBarendtime() {
      java.lang.Object ref = barendtime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          barendtime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string barendtime = 7;</code>
     */
    public com.google.protobuf.ByteString
        getBarendtimeBytes() {
      java.lang.Object ref = barendtime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        barendtime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TURNOVER_FIELD_NUMBER = 8;
    private float turnover_;
    /**
     * <code>required float turnover = 8;</code>
     */
    public boolean hasTurnover() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required float turnover = 8;</code>
     */
    public float getTurnover() {
      return turnover_;
    }

    public static final int DAY_FIELD_NUMBER = 9;
    private java.lang.Object day_;
    /**
     * <code>required string day = 9;</code>
     */
    public boolean hasDay() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string day = 9;</code>
     */
    public java.lang.String getDay() {
      java.lang.Object ref = day_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          day_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string day = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDayBytes() {
      java.lang.Object ref = day_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        day_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      high_ = 0F;
      low_ = 0F;
      open_ = 0F;
      close_ = 0F;
      volume_ = 0F;
      bartime_ = "";
      barendtime_ = "";
      turnover_ = 0F;
      day_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHigh()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOpen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClose()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVolume()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBartime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBarendtime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTurnover()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, high_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, low_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, open_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, close_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, volume_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getBartimeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getBarendtimeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(8, turnover_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getDayBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, high_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, low_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, open_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, close_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, volume_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getBartimeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getBarendtimeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, turnover_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getDayBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static FutureMin.future_min parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FutureMin.future_min parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FutureMin.future_min parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FutureMin.future_min parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FutureMin.future_min parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static FutureMin.future_min parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static FutureMin.future_min parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static FutureMin.future_min parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static FutureMin.future_min parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static FutureMin.future_min parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(FutureMin.future_min prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code future_min}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:future_min)
        FutureMin.future_minOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FutureMin.internal_static_future_min_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FutureMin.internal_static_future_min_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FutureMin.future_min.class, FutureMin.future_min.Builder.class);
      }

      // Construct using FutureMin.future_min.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        high_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        low_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        open_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        close_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        volume_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        bartime_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        barendtime_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        turnover_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        day_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FutureMin.internal_static_future_min_descriptor;
      }

      public FutureMin.future_min getDefaultInstanceForType() {
        return FutureMin.future_min.getDefaultInstance();
      }

      public FutureMin.future_min build() {
        FutureMin.future_min result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public FutureMin.future_min buildPartial() {
        FutureMin.future_min result = new FutureMin.future_min(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.high_ = high_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.low_ = low_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.open_ = open_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.close_ = close_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.volume_ = volume_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.bartime_ = bartime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.barendtime_ = barendtime_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.turnover_ = turnover_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.day_ = day_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FutureMin.future_min) {
          return mergeFrom((FutureMin.future_min)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FutureMin.future_min other) {
        if (other == FutureMin.future_min.getDefaultInstance()) return this;
        if (other.hasHigh()) {
          setHigh(other.getHigh());
        }
        if (other.hasLow()) {
          setLow(other.getLow());
        }
        if (other.hasOpen()) {
          setOpen(other.getOpen());
        }
        if (other.hasClose()) {
          setClose(other.getClose());
        }
        if (other.hasVolume()) {
          setVolume(other.getVolume());
        }
        if (other.hasBartime()) {
          bitField0_ |= 0x00000020;
          bartime_ = other.bartime_;
          onChanged();
        }
        if (other.hasBarendtime()) {
          bitField0_ |= 0x00000040;
          barendtime_ = other.barendtime_;
          onChanged();
        }
        if (other.hasTurnover()) {
          setTurnover(other.getTurnover());
        }
        if (other.hasDay()) {
          bitField0_ |= 0x00000100;
          day_ = other.day_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHigh()) {
          
          return false;
        }
        if (!hasLow()) {
          
          return false;
        }
        if (!hasOpen()) {
          
          return false;
        }
        if (!hasClose()) {
          
          return false;
        }
        if (!hasVolume()) {
          
          return false;
        }
        if (!hasBartime()) {
          
          return false;
        }
        if (!hasBarendtime()) {
          
          return false;
        }
        if (!hasTurnover()) {
          
          return false;
        }
        if (!hasDay()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FutureMin.future_min parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FutureMin.future_min) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float high_ ;
      /**
       * <code>required float high = 1;</code>
       */
      public boolean hasHigh() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float high = 1;</code>
       */
      public float getHigh() {
        return high_;
      }
      /**
       * <code>required float high = 1;</code>
       */
      public Builder setHigh(float value) {
        bitField0_ |= 0x00000001;
        high_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float high = 1;</code>
       */
      public Builder clearHigh() {
        bitField0_ = (bitField0_ & ~0x00000001);
        high_ = 0F;
        onChanged();
        return this;
      }

      private float low_ ;
      /**
       * <code>required float low = 2;</code>
       */
      public boolean hasLow() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float low = 2;</code>
       */
      public float getLow() {
        return low_;
      }
      /**
       * <code>required float low = 2;</code>
       */
      public Builder setLow(float value) {
        bitField0_ |= 0x00000002;
        low_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float low = 2;</code>
       */
      public Builder clearLow() {
        bitField0_ = (bitField0_ & ~0x00000002);
        low_ = 0F;
        onChanged();
        return this;
      }

      private float open_ ;
      /**
       * <code>required float open = 3;</code>
       */
      public boolean hasOpen() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float open = 3;</code>
       */
      public float getOpen() {
        return open_;
      }
      /**
       * <code>required float open = 3;</code>
       */
      public Builder setOpen(float value) {
        bitField0_ |= 0x00000004;
        open_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float open = 3;</code>
       */
      public Builder clearOpen() {
        bitField0_ = (bitField0_ & ~0x00000004);
        open_ = 0F;
        onChanged();
        return this;
      }

      private float close_ ;
      /**
       * <code>required float close = 4;</code>
       */
      public boolean hasClose() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float close = 4;</code>
       */
      public float getClose() {
        return close_;
      }
      /**
       * <code>required float close = 4;</code>
       */
      public Builder setClose(float value) {
        bitField0_ |= 0x00000008;
        close_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float close = 4;</code>
       */
      public Builder clearClose() {
        bitField0_ = (bitField0_ & ~0x00000008);
        close_ = 0F;
        onChanged();
        return this;
      }

      private float volume_ ;
      /**
       * <code>required float volume = 5;</code>
       */
      public boolean hasVolume() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required float volume = 5;</code>
       */
      public float getVolume() {
        return volume_;
      }
      /**
       * <code>required float volume = 5;</code>
       */
      public Builder setVolume(float value) {
        bitField0_ |= 0x00000010;
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float volume = 5;</code>
       */
      public Builder clearVolume() {
        bitField0_ = (bitField0_ & ~0x00000010);
        volume_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object bartime_ = "";
      /**
       * <code>required string bartime = 6;</code>
       */
      public boolean hasBartime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string bartime = 6;</code>
       */
      public java.lang.String getBartime() {
        java.lang.Object ref = bartime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bartime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string bartime = 6;</code>
       */
      public com.google.protobuf.ByteString
          getBartimeBytes() {
        java.lang.Object ref = bartime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bartime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string bartime = 6;</code>
       */
      public Builder setBartime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        bartime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string bartime = 6;</code>
       */
      public Builder clearBartime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bartime_ = getDefaultInstance().getBartime();
        onChanged();
        return this;
      }
      /**
       * <code>required string bartime = 6;</code>
       */
      public Builder setBartimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        bartime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object barendtime_ = "";
      /**
       * <code>required string barendtime = 7;</code>
       */
      public boolean hasBarendtime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string barendtime = 7;</code>
       */
      public java.lang.String getBarendtime() {
        java.lang.Object ref = barendtime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            barendtime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string barendtime = 7;</code>
       */
      public com.google.protobuf.ByteString
          getBarendtimeBytes() {
        java.lang.Object ref = barendtime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          barendtime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string barendtime = 7;</code>
       */
      public Builder setBarendtime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        barendtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string barendtime = 7;</code>
       */
      public Builder clearBarendtime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        barendtime_ = getDefaultInstance().getBarendtime();
        onChanged();
        return this;
      }
      /**
       * <code>required string barendtime = 7;</code>
       */
      public Builder setBarendtimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        barendtime_ = value;
        onChanged();
        return this;
      }

      private float turnover_ ;
      /**
       * <code>required float turnover = 8;</code>
       */
      public boolean hasTurnover() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required float turnover = 8;</code>
       */
      public float getTurnover() {
        return turnover_;
      }
      /**
       * <code>required float turnover = 8;</code>
       */
      public Builder setTurnover(float value) {
        bitField0_ |= 0x00000080;
        turnover_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float turnover = 8;</code>
       */
      public Builder clearTurnover() {
        bitField0_ = (bitField0_ & ~0x00000080);
        turnover_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object day_ = "";
      /**
       * <code>required string day = 9;</code>
       */
      public boolean hasDay() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string day = 9;</code>
       */
      public java.lang.String getDay() {
        java.lang.Object ref = day_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            day_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string day = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDayBytes() {
        java.lang.Object ref = day_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          day_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string day = 9;</code>
       */
      public Builder setDay(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string day = 9;</code>
       */
      public Builder clearDay() {
        bitField0_ = (bitField0_ & ~0x00000100);
        day_ = getDefaultInstance().getDay();
        onChanged();
        return this;
      }
      /**
       * <code>required string day = 9;</code>
       */
      public Builder setDayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        day_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:future_min)
    }

    static {
      defaultInstance = new future_min(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:future_min)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_future_min_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_future_min_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020future_min.proto\"\230\001\n\nfuture_min\022\014\n\004hig" +
      "h\030\001 \002(\002\022\013\n\003low\030\002 \002(\002\022\014\n\004open\030\003 \002(\002\022\r\n\005cl" +
      "ose\030\004 \002(\002\022\016\n\006volume\030\005 \002(\002\022\017\n\007bartime\030\006 \002" +
      "(\t\022\022\n\nbarendtime\030\007 \002(\t\022\020\n\010turnover\030\010 \002(\002" +
      "\022\013\n\003day\030\t \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_future_min_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_future_min_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_future_min_descriptor,
        new java.lang.String[] { "High", "Low", "Open", "Close", "Volume", "Bartime", "Barendtime", "Turnover", "Day", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
