// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: l2.proto

public final class L2 {
  private L2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface market_priceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:market_price)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float high = 1;</code>
     */
    boolean hasHigh();
    /**
     * <code>required float high = 1;</code>
     */
    float getHigh();

    /**
     * <code>required float low = 2;</code>
     */
    boolean hasLow();
    /**
     * <code>required float low = 2;</code>
     */
    float getLow();

    /**
     * <code>required float open = 3;</code>
     */
    boolean hasOpen();
    /**
     * <code>required float open = 3;</code>
     */
    float getOpen();

    /**
     * <code>required float close = 4;</code>
     */
    boolean hasClose();
    /**
     * <code>required float close = 4;</code>
     */
    float getClose();

    /**
     * <code>required float volume = 5;</code>
     */
    boolean hasVolume();
    /**
     * <code>required float volume = 5;</code>
     */
    float getVolume();

    /**
     * <code>required float time_stamp = 6;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>required float time_stamp = 6;</code>
     */
    float getTimeStamp();

    /**
     * <code>optional string code = 7;</code>
     */
    boolean hasCode();
    /**
     * <code>optional string code = 7;</code>
     */
    java.lang.String getCode();
    /**
     * <code>optional string code = 7;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();
  }
  /**
   * Protobuf type {@code market_price}
   */
  public static final class market_price extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:market_price)
      market_priceOrBuilder {
    // Use market_price.newBuilder() to construct.
    private market_price(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private market_price(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final market_price defaultInstance;
    public static market_price getDefaultInstance() {
      return defaultInstance;
    }

    public market_price getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private market_price(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              high_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              low_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              open_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              close_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              volume_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              timeStamp_ = input.readFloat();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              code_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return L2.internal_static_market_price_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return L2.internal_static_market_price_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              L2.market_price.class, L2.market_price.Builder.class);
    }

    public static com.google.protobuf.Parser<market_price> PARSER =
        new com.google.protobuf.AbstractParser<market_price>() {
      public market_price parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new market_price(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<market_price> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code market_price.market_holder}
     */
    public enum market_holder
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>sh = 0;</code>
       */
      sh(0, 0),
      /**
       * <code>sz = 1;</code>
       */
      sz(1, 1),
      ;

      /**
       * <code>sh = 0;</code>
       */
      public static final int sh_VALUE = 0;
      /**
       * <code>sz = 1;</code>
       */
      public static final int sz_VALUE = 1;


      public final int getNumber() { return value; }

      public static market_holder valueOf(int value) {
        switch (value) {
          case 0: return sh;
          case 1: return sz;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<market_holder>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<market_holder>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<market_holder>() {
              public market_holder findValueByNumber(int number) {
                return market_holder.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return L2.market_price.getDescriptor().getEnumTypes().get(0);
      }

      private static final market_holder[] VALUES = values();

      public static market_holder valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private market_holder(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:market_price.market_holder)
    }

    public interface market_infoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:market_price.market_info)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required .market_price.market_holder type = 1 [default = sh];</code>
       */
      boolean hasType();
      /**
       * <code>required .market_price.market_holder type = 1 [default = sh];</code>
       */
      L2.market_price.market_holder getType();
    }
    /**
     * Protobuf type {@code market_price.market_info}
     */
    public static final class market_info extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:market_price.market_info)
        market_infoOrBuilder {
      // Use market_info.newBuilder() to construct.
      private market_info(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private market_info(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final market_info defaultInstance;
      public static market_info getDefaultInstance() {
        return defaultInstance;
      }

      public market_info getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private market_info(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                L2.market_price.market_holder value = L2.market_price.market_holder.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  type_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return L2.internal_static_market_price_market_info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return L2.internal_static_market_price_market_info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                L2.market_price.market_info.class, L2.market_price.market_info.Builder.class);
      }

      public static com.google.protobuf.Parser<market_info> PARSER =
          new com.google.protobuf.AbstractParser<market_info>() {
        public market_info parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new market_info(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<market_info> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int TYPE_FIELD_NUMBER = 1;
      private L2.market_price.market_holder type_;
      /**
       * <code>required .market_price.market_holder type = 1 [default = sh];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .market_price.market_holder type = 1 [default = sh];</code>
       */
      public L2.market_price.market_holder getType() {
        return type_;
      }

      private void initFields() {
        type_ = L2.market_price.market_holder.sh;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, type_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, type_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static L2.market_price.market_info parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static L2.market_price.market_info parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static L2.market_price.market_info parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static L2.market_price.market_info parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static L2.market_price.market_info parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static L2.market_price.market_info parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static L2.market_price.market_info parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static L2.market_price.market_info parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static L2.market_price.market_info parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static L2.market_price.market_info parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(L2.market_price.market_info prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code market_price.market_info}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:market_price.market_info)
          L2.market_price.market_infoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return L2.internal_static_market_price_market_info_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return L2.internal_static_market_price_market_info_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  L2.market_price.market_info.class, L2.market_price.market_info.Builder.class);
        }

        // Construct using L2.market_price.market_info.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          type_ = L2.market_price.market_holder.sh;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return L2.internal_static_market_price_market_info_descriptor;
        }

        public L2.market_price.market_info getDefaultInstanceForType() {
          return L2.market_price.market_info.getDefaultInstance();
        }

        public L2.market_price.market_info build() {
          L2.market_price.market_info result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public L2.market_price.market_info buildPartial() {
          L2.market_price.market_info result = new L2.market_price.market_info(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof L2.market_price.market_info) {
            return mergeFrom((L2.market_price.market_info)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(L2.market_price.market_info other) {
          if (other == L2.market_price.market_info.getDefaultInstance()) return this;
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasType()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          L2.market_price.market_info parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (L2.market_price.market_info) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private L2.market_price.market_holder type_ = L2.market_price.market_holder.sh;
        /**
         * <code>required .market_price.market_holder type = 1 [default = sh];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .market_price.market_holder type = 1 [default = sh];</code>
         */
        public L2.market_price.market_holder getType() {
          return type_;
        }
        /**
         * <code>required .market_price.market_holder type = 1 [default = sh];</code>
         */
        public Builder setType(L2.market_price.market_holder value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .market_price.market_holder type = 1 [default = sh];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = L2.market_price.market_holder.sh;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:market_price.market_info)
      }

      static {
        defaultInstance = new market_info(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:market_price.market_info)
    }

    private int bitField0_;
    public static final int HIGH_FIELD_NUMBER = 1;
    private float high_;
    /**
     * <code>required float high = 1;</code>
     */
    public boolean hasHigh() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float high = 1;</code>
     */
    public float getHigh() {
      return high_;
    }

    public static final int LOW_FIELD_NUMBER = 2;
    private float low_;
    /**
     * <code>required float low = 2;</code>
     */
    public boolean hasLow() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float low = 2;</code>
     */
    public float getLow() {
      return low_;
    }

    public static final int OPEN_FIELD_NUMBER = 3;
    private float open_;
    /**
     * <code>required float open = 3;</code>
     */
    public boolean hasOpen() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float open = 3;</code>
     */
    public float getOpen() {
      return open_;
    }

    public static final int CLOSE_FIELD_NUMBER = 4;
    private float close_;
    /**
     * <code>required float close = 4;</code>
     */
    public boolean hasClose() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float close = 4;</code>
     */
    public float getClose() {
      return close_;
    }

    public static final int VOLUME_FIELD_NUMBER = 5;
    private float volume_;
    /**
     * <code>required float volume = 5;</code>
     */
    public boolean hasVolume() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required float volume = 5;</code>
     */
    public float getVolume() {
      return volume_;
    }

    public static final int TIME_STAMP_FIELD_NUMBER = 6;
    private float timeStamp_;
    /**
     * <code>required float time_stamp = 6;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required float time_stamp = 6;</code>
     */
    public float getTimeStamp() {
      return timeStamp_;
    }

    public static final int CODE_FIELD_NUMBER = 7;
    private java.lang.Object code_;
    /**
     * <code>optional string code = 7;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string code = 7;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string code = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      high_ = 0F;
      low_ = 0F;
      open_ = 0F;
      close_ = 0F;
      volume_ = 0F;
      timeStamp_ = 0F;
      code_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHigh()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOpen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClose()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVolume()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, high_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, low_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, open_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, close_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, volume_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, timeStamp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getCodeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, high_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, low_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, open_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, close_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, volume_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, timeStamp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getCodeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static L2.market_price parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static L2.market_price parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static L2.market_price parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static L2.market_price parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static L2.market_price parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static L2.market_price parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static L2.market_price parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static L2.market_price parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static L2.market_price parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static L2.market_price parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(L2.market_price prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code market_price}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:market_price)
        L2.market_priceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return L2.internal_static_market_price_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return L2.internal_static_market_price_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                L2.market_price.class, L2.market_price.Builder.class);
      }

      // Construct using L2.market_price.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        high_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        low_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        open_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        close_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        volume_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        timeStamp_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return L2.internal_static_market_price_descriptor;
      }

      public L2.market_price getDefaultInstanceForType() {
        return L2.market_price.getDefaultInstance();
      }

      public L2.market_price build() {
        L2.market_price result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public L2.market_price buildPartial() {
        L2.market_price result = new L2.market_price(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.high_ = high_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.low_ = low_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.open_ = open_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.close_ = close_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.volume_ = volume_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof L2.market_price) {
          return mergeFrom((L2.market_price)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(L2.market_price other) {
        if (other == L2.market_price.getDefaultInstance()) return this;
        if (other.hasHigh()) {
          setHigh(other.getHigh());
        }
        if (other.hasLow()) {
          setLow(other.getLow());
        }
        if (other.hasOpen()) {
          setOpen(other.getOpen());
        }
        if (other.hasClose()) {
          setClose(other.getClose());
        }
        if (other.hasVolume()) {
          setVolume(other.getVolume());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasCode()) {
          bitField0_ |= 0x00000040;
          code_ = other.code_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHigh()) {
          
          return false;
        }
        if (!hasLow()) {
          
          return false;
        }
        if (!hasOpen()) {
          
          return false;
        }
        if (!hasClose()) {
          
          return false;
        }
        if (!hasVolume()) {
          
          return false;
        }
        if (!hasTimeStamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        L2.market_price parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (L2.market_price) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float high_ ;
      /**
       * <code>required float high = 1;</code>
       */
      public boolean hasHigh() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float high = 1;</code>
       */
      public float getHigh() {
        return high_;
      }
      /**
       * <code>required float high = 1;</code>
       */
      public Builder setHigh(float value) {
        bitField0_ |= 0x00000001;
        high_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float high = 1;</code>
       */
      public Builder clearHigh() {
        bitField0_ = (bitField0_ & ~0x00000001);
        high_ = 0F;
        onChanged();
        return this;
      }

      private float low_ ;
      /**
       * <code>required float low = 2;</code>
       */
      public boolean hasLow() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float low = 2;</code>
       */
      public float getLow() {
        return low_;
      }
      /**
       * <code>required float low = 2;</code>
       */
      public Builder setLow(float value) {
        bitField0_ |= 0x00000002;
        low_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float low = 2;</code>
       */
      public Builder clearLow() {
        bitField0_ = (bitField0_ & ~0x00000002);
        low_ = 0F;
        onChanged();
        return this;
      }

      private float open_ ;
      /**
       * <code>required float open = 3;</code>
       */
      public boolean hasOpen() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float open = 3;</code>
       */
      public float getOpen() {
        return open_;
      }
      /**
       * <code>required float open = 3;</code>
       */
      public Builder setOpen(float value) {
        bitField0_ |= 0x00000004;
        open_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float open = 3;</code>
       */
      public Builder clearOpen() {
        bitField0_ = (bitField0_ & ~0x00000004);
        open_ = 0F;
        onChanged();
        return this;
      }

      private float close_ ;
      /**
       * <code>required float close = 4;</code>
       */
      public boolean hasClose() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float close = 4;</code>
       */
      public float getClose() {
        return close_;
      }
      /**
       * <code>required float close = 4;</code>
       */
      public Builder setClose(float value) {
        bitField0_ |= 0x00000008;
        close_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float close = 4;</code>
       */
      public Builder clearClose() {
        bitField0_ = (bitField0_ & ~0x00000008);
        close_ = 0F;
        onChanged();
        return this;
      }

      private float volume_ ;
      /**
       * <code>required float volume = 5;</code>
       */
      public boolean hasVolume() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required float volume = 5;</code>
       */
      public float getVolume() {
        return volume_;
      }
      /**
       * <code>required float volume = 5;</code>
       */
      public Builder setVolume(float value) {
        bitField0_ |= 0x00000010;
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float volume = 5;</code>
       */
      public Builder clearVolume() {
        bitField0_ = (bitField0_ & ~0x00000010);
        volume_ = 0F;
        onChanged();
        return this;
      }

      private float timeStamp_ ;
      /**
       * <code>required float time_stamp = 6;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required float time_stamp = 6;</code>
       */
      public float getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>required float time_stamp = 6;</code>
       */
      public Builder setTimeStamp(float value) {
        bitField0_ |= 0x00000020;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float time_stamp = 6;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timeStamp_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <code>optional string code = 7;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string code = 7;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string code = 7;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string code = 7;</code>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string code = 7;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000040);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string code = 7;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        code_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:market_price)
    }

    static {
      defaultInstance = new market_price(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:market_price)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_market_price_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_market_price_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_market_price_market_info_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_market_price_market_info_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010l2.proto\"\327\001\n\014market_price\022\014\n\004high\030\001 \002(" +
      "\002\022\013\n\003low\030\002 \002(\002\022\014\n\004open\030\003 \002(\002\022\r\n\005close\030\004 " +
      "\002(\002\022\016\n\006volume\030\005 \002(\002\022\022\n\ntime_stamp\030\006 \002(\002\022" +
      "\014\n\004code\030\007 \001(\t\032<\n\013market_info\022-\n\004type\030\001 \002" +
      "(\0162\033.market_price.market_holder:\002sh\"\037\n\rm" +
      "arket_holder\022\006\n\002sh\020\000\022\006\n\002sz\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_market_price_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_market_price_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_market_price_descriptor,
        new java.lang.String[] { "High", "Low", "Open", "Close", "Volume", "TimeStamp", "Code", });
    internal_static_market_price_market_info_descriptor =
      internal_static_market_price_descriptor.getNestedTypes().get(0);
    internal_static_market_price_market_info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_market_price_market_info_descriptor,
        new java.lang.String[] { "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
