# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: l2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='l2.proto',
  package='',
  serialized_pb=_b('\n\x08l2.proto\"\xd7\x01\n\x0cmarket_price\x12\x0c\n\x04high\x18\x01 \x02(\x02\x12\x0b\n\x03low\x18\x02 \x02(\x02\x12\x0c\n\x04open\x18\x03 \x02(\x02\x12\r\n\x05\x63lose\x18\x04 \x02(\x02\x12\x0e\n\x06volume\x18\x05 \x02(\x02\x12\x12\n\ntime_stamp\x18\x06 \x02(\x02\x12\x0c\n\x04\x63ode\x18\x07 \x01(\t\x1a<\n\x0bmarket_info\x12-\n\x04type\x18\x01 \x02(\x0e\x32\x1b.market_price.market_holder:\x02sh\"\x1f\n\rmarket_holder\x12\x06\n\x02sh\x10\x00\x12\x06\n\x02sz\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MARKET_PRICE_MARKET_HOLDER = _descriptor.EnumDescriptor(
  name='market_holder',
  full_name='market_price.market_holder',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='sh', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sz', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=197,
  serialized_end=228,
)
_sym_db.RegisterEnumDescriptor(_MARKET_PRICE_MARKET_HOLDER)


_MARKET_PRICE_MARKET_INFO = _descriptor.Descriptor(
  name='market_info',
  full_name='market_price.market_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='market_price.market_info.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=195,
)

_MARKET_PRICE = _descriptor.Descriptor(
  name='market_price',
  full_name='market_price',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='high', full_name='market_price.high', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='low', full_name='market_price.low', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='open', full_name='market_price.open', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='close', full_name='market_price.close', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volume', full_name='market_price.volume', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='market_price.time_stamp', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='market_price.code', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MARKET_PRICE_MARKET_INFO, ],
  enum_types=[
    _MARKET_PRICE_MARKET_HOLDER,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=228,
)

_MARKET_PRICE_MARKET_INFO.fields_by_name['type'].enum_type = _MARKET_PRICE_MARKET_HOLDER
_MARKET_PRICE_MARKET_INFO.containing_type = _MARKET_PRICE
_MARKET_PRICE_MARKET_HOLDER.containing_type = _MARKET_PRICE
DESCRIPTOR.message_types_by_name['market_price'] = _MARKET_PRICE

market_price = _reflection.GeneratedProtocolMessageType('market_price', (_message.Message,), dict(

  market_info = _reflection.GeneratedProtocolMessageType('market_info', (_message.Message,), dict(
    DESCRIPTOR = _MARKET_PRICE_MARKET_INFO,
    __module__ = 'l2_pb2'
    # @@protoc_insertion_point(class_scope:market_price.market_info)
    ))
  ,
  DESCRIPTOR = _MARKET_PRICE,
  __module__ = 'l2_pb2'
  # @@protoc_insertion_point(class_scope:market_price)
  ))
_sym_db.RegisterMessage(market_price)
_sym_db.RegisterMessage(market_price.market_info)


# @@protoc_insertion_point(module_scope)
